Repository tari-project/tari-crypto, pull requests merged in 2022-10, with the labels that each got.

#133 ci: clippy all features
  .github/workflows/clippy-check.yml
Labels: P-merge

#137 feat: add `Zeroize` support to key types, and create new shared secret type
  src/dhke.rs
  src/keys.rs
  src/lib.rs
  src/ristretto/ristretto_keys.rs
Labels: P-merge

#136 feat: use precomputation for default commitments
  benches/commitment.rs
  benches/mod.rs
  src/ristretto/constants.rs
  src/ristretto/pedersen/commitment_factory.rs
Labels: P-acks_required

#138 chore: fix various clippy errors
  .github/workflows/check_licence.yml
  .github/workflows/clippy-check.yml
  benches/commitment.rs
  rustfmt.toml
  src/dhke.rs
  src/hashing.rs
  src/ristretto/bulletproofs_plus.rs
  src/ristretto/constants.rs
  src/ristretto/ristretto_com_sig.rs
  src/ristretto/ristretto_keys.rs
  src/ristretto/ristretto_sig.rs
Labels: P-merge

#131 feat: add new commitment signature to use complete representation proof
  src/ffi/keys.rs
  src/ffi/mod.rs
  src/ristretto/mod.rs
  src/ristretto/ristretto_com_and_pub_sig.rs
  src/signatures/commitment_and_public_key_signature.rs
  src/signatures/commitment_signature.rs
  src/signatures/mod.rs
  src/wasm/key_utils.rs
Labels: CR-too_long, P-acks_required
