Repository tari-project/tari-crypto, pull requests merged in 2023-09, with the labels that each got.

#203 test: replace usize with u64
  src/ristretto/constants.rs
Labels: CR-insufficient_context, P-acks_required

#206 ci: update CI actions
  .github/workflows/audit.yml
  .github/workflows/check_licence.yml
  .github/workflows/clippy-check.yml
  .github/workflows/source-cov.yml
  .github/workflows/test.yml
Labels: P-acks_required

#207 test: expand and clean up lints
  lints.toml
Labels: P-acks_required

#194 feat!: differentiate scalar parsing from byte arrays
  Cargo.toml
  benches/signatures.rs
  src/commitment.rs
  src/errors.rs
  src/hashing.rs
  src/keys.rs
  src/ristretto/mod.rs
  src/ristretto/pedersen/mod.rs
  src/ristretto/ristretto_com_and_pub_sig.rs
  src/ristretto/ristretto_com_sig.rs
  src/ristretto/ristretto_keys.rs
  src/ristretto/ristretto_sig.rs
  src/ristretto/serialize.rs
  src/ristretto/utils.rs
  src/signatures/commitment_and_public_key_signature.rs
  src/signatures/commitment_signature.rs
  src/signatures/schnorr.rs
Labels: P-merge
