Repository tari-project/tari-crypto, pull requests merged in 2023-08, with the labels that each got.

#190 chore: fix a spurious lint
  src/ristretto/bulletproofs_plus.rs
Labels: P-acks_required

#192 feat: fix new_generator
  src/ristretto/ristretto_keys.rs
Labels: P-acks_required

#187 chore: update dependencies
  Cargo.toml
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#193 feat!: move the WASM and FFI builds to seperate Repos
  .cargo/config.toml
  .github/workflows/test.yml
  .github/workflows/wasm.yml
  Cargo.toml
  Makefile
  README.md
  build.rs
  cbindgen.toml
  libtari/demo.c
  src/ffi/error.rs
  src/ffi/keys.rs
  src/ffi/mod.rs
  src/lib.rs
  src/wasm/commitments.rs
  src/wasm/key_utils.rs
  src/wasm/keyring.rs
  src/wasm/mod.rs
  src/wasm/range_proofs.rs
  wasm-demo.js
  wasm.sh
Labels: P-acks_required

#191 feat!: enable no_std support for tari_crypto
  .github/workflows/clippy-check.yml
  Cargo.toml
  README.md
  benches/signatures.rs
  src/commitment.rs
  src/deterministic_randomizer.rs
  src/dhke.rs
  src/errors.rs
  src/extended_range_proof.rs
  src/hashing.rs
  src/keys.rs
  src/lib.rs
  src/ristretto/bulletproofs_plus.rs
  src/ristretto/constants.rs
  src/ristretto/mod.rs
  src/ristretto/pedersen/commitment_factory.rs
  src/ristretto/pedersen/extended_commitment_factory.rs
  src/ristretto/pedersen/mod.rs
  src/ristretto/ristretto_keys.rs
  src/ristretto/ristretto_sig.rs
  src/ristretto/serialize.rs
  src/ristretto/utils.rs
  src/signatures/commitment_and_public_key_signature.rs
  src/signatures/commitment_signature.rs
  src/signatures/schnorr.rs
Labels: CR-insufficient_context, P-acks_required

#195 chore: release 0.18.0
  Cargo.toml
  changelog.md
Labels: P-acks_required

#198 chore: remove unused rewindable range proof code
  src/lib.rs
  src/rewindable_range_proof.rs
Labels: CR-insufficient_context, P-acks_required

#197 feat: simplify zeroizing and add test to DHKE
  src/dhke.rs
Labels: P-acks_required
